FROM mcr.microsoft.com/playwright/python:latest-arm64

ENV PIP_ROOT_USER_ACTION=ignore

RUN mkdir /workspace/
WORKDIR /workspace/
ADD . /workspace/

RUN apt update && \
    apt install dumb-init && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r docker/requirements.txt

ENTRYPOINT ["/usr/bin/dumb-init", "--", "uvicorn", "docker.server:app"]
